This is an exception
   at Progress.Test.Tools.ExampleTestClass.CausesError() in test\Tools\ExceptionPrettifierTest.cs:line 15
   at Progress.Test.Tools.ExceptionPrettifierTest.TrivialStackTraceWorks() in test\Tools\ExceptionPrettifierTest.cs:line 39
